### PR TITLE
prime-factors: accept order-independent results

### LINKED ISSUE #1295: prime-factors: fails despite valid output
Since the test file use `reflect.DeepEqual`, the slice values must appear in the exact same order to be considered equal. This is poor behaviour because the requirements do not specify ordering. 

Thus `int64[]{2, 3, 2}` fails for the expected output `[]int64{2, 2, 3}`. 

Solution: 
1. Custom implementation of equality that doesn't rely on order.
2. Sort the slice before using `reflect.DeepEqual` in the test harness.

### PR DESCRIPTION
**Pull request by JackMordaunt**
Fix #1295 

Simple sort implementation applied to the list of primes before testing for equality.

### CODE REVIEW

File: exercises/prime-factors/prime_factors_test.go [hunk 1]
```diff
@@ -1,15 +1,15 @@
...
 import (
 	"reflect"
+	"sort"
 	"testing"
 )
 
 func TestPrimeFactors(t *testing.T) {
 	for _, test := range tests {
 		actual := Factors(test.input)
+		sort.Sort(ascending(actual))
```
Comment (ferhatelmas) [inline exercises/prime-factors/prime_factors_test.go]: IMHO, using [sort.Slice](https://golang.org/pkg/sort/#Slice) would make it simpler

**Comment by ferhatelmas** [comment]
> Note: Assumes the test cases are already sorted in ascending order.

let's ensure it too since we dropped order requirement, it would be safer.

File: exercises/prime-factors/prime_factors_test.go [hunk 2]
```diff
@@ -1,15 +1,16 @@
...
 	"reflect"
+	"sort"
 	"testing"
 )
 
 func TestPrimeFactors(t *testing.T) {
 	for _, test := range tests {
 		actual := Factors(test.input)
+		sort.Slice(actual, ascending(actual))
+		sort.Slice(test.expected, ascending(test.expected))
```
Comment (tehsphinx) [inline exercises/prime-factors/prime_factors_test.go]: I think this needs to be:

```suggestion
		sort.Slice(test.expected, ascending)
```

Same above.

`func Slice(slice interface{}, less func(i, j int) bool)` expects a function as second argument.

Comment (JackMordaunt) [reply exercises/prime-factors/prime_factors_test.go]: Yes, my function returns a closure.

Comment (tehsphinx) [reply exercises/prime-factors/prime_factors_test.go]: see also the example on https://golang.org/pkg/sort/#Slice

File: exercises/prime-factors/prime_factors_test.go (hunk 1 above)
Comment (JackMordaunt) [reply exercises/prime-factors/prime_factors_test.go]: I tried in-lining the sorting funcs, but it gets verbose: 

```go
sort.Slice(actual, func(ii, jj int) bool {return actual[ii] < actual[jj]})
sort.Slice(test.expected, func(ii, jj int) bool {return test.expected[ii] < test.expected[jj]})
```

So I opted for a named func. Similar in LOC to the previous sort impl.

File: exercises/prime-factors/prime_factors_test.go (hunk 2 above)
Comment (tehsphinx) [reply exercises/prime-factors/prime_factors_test.go]: right...  my bad. I guess I'm tired :D

File: exercises/prime-factors/prime_factors_test.go (hunk 1 above)
Comment (ferhatelmas) [reply exercises/prime-factors/prime_factors_test.go]: thanks, a func sounds good.

File: exercises/prime-factors/prime_factors_test.go [hunk 3]
```diff
@@ -26,3 +27,9 @@ func BenchmarkPrimeFactors(b *testing.B) {
 		}
 	}
 }
+
+func ascending(list []int64) func(int, int) bool {
+	return func(ii, jj int) bool {
+		return list[ii] < list[jj]
```
Comment (ferhatelmas) [inline exercises/prime-factors/prime_factors_test.go]: why not `i` and `j` ?

**Comment by ferhatelmas** [comment]
@JackMordaunt removed note regarding expected from the PR description.

File: exercises/prime-factors/prime_factors_test.go (hunk 3 above)
Comment (JackMordaunt) [reply exercises/prime-factors/prime_factors_test.go]: It's a habit of mine. Easier to identify / search for `ii` than `i`, which appears in many English words.

Comment (ferhatelmas) [reply exercises/prime-factors/prime_factors_test.go]: I think it's better, let's change it then good to go. Thanks!

**Comment by ferhatelmas** [comment]
@JackMordaunt awesome contribution, thanks a lot. 

There are a lot to help if you would like to do more. Be sure to read: https://github.com/exercism/go/issues/1304

**Comment by JackMordaunt** [comment]
Thanks! I'll take a look, you might see me some more.

**Comment by tehsphinx** [comment]
@ferhatelmas Are you also taking part in the `v3` initiative? (#1304)

We are just starting to organize ourselves in exercism Slack channel `maintaining-go`.

**Comment by ferhatelmas** [comment]
@tehsphinx yes but I need to read a bit what to do. Probably will do tomorrow. 

If there is something I can, ping me there, will give a look.

**Comment by ferhatelmas** [comment]
@tehsphinx could you shoot an invite for slack ? `elmas.ferhat` at google mail.

**Comment by tehsphinx** [comment]
@ferhatelmas I requested an invitation for you.
