### PR TITLE
Saddle Points: Remove inconsistent instructions from test file - Fixes #2482

### LINKED ISSUE #2482: Saddle Points - Directions / Comments Incorrect
saddle_points_test.go contains the following incorrect comment. 

```go
// Short cut!  Have you already done the matrix exercise?
// If it seems helpful, copy your code from the matrix exercise
// to this directory so you have access to it.  You can leave it as matrix.go
// and start a new file saddle_points.go with additional code that completes
// this exercise.  Submit only saddle_points.go for this exercise.
```

The key point `Submit only saddle_points.go for this exercise.` will result in online tests failing while local tests succeed. 

I propose changing this to `Submit both saddle_points.go and matrix.go for this exercise.` which allows the online tests to pass. 

Alternatively, the comment could be removed entirely suggesting that all solution code must be created and uploaded. 

I will submit a PR to resolve once the solution is agreed.

### PR DESCRIPTION
**Pull request by W8CYE**
Removed "Submit only saddle_points.go for this exercise." from the end of the following comment section in `saddle_points_test.go`.

```
// Short cut!  Have you already done the matrix exercise?
// If it seems helpful, copy your code from the matrix exercise
// to this directory so you have access to it.  You can leave it as matrix.go
// and start a new file saddle_points.go with additional code that completes
// this exercise.
```

Tests would fail if the student used matrix.go and failed to upload it.

Fixes https://github.com/exercism/go/issues/2482

### CODE REVIEW

File: exercises/practice/saddle-points/saddle_points_test.go [hunk 1]
```diff
@@ -2,7 +2,7 @@
 // If it seems helpful, copy your code from the matrix exercise
 // to this directory so you have access to it.  You can leave it as matrix.go
 // and start a new file saddle_points.go with additional code that completes
-// this exercise.  Submit only saddle_points.go for this exercise.
+// this exercise.
```
Comment (andrerfcsantos) [inline exercises/practice/saddle-points/saddle_points_test.go:5]:
```suggestion
// this exercise. If you do copy the matrix.go file, do not forget to submit both
// saddle_points.go and matrix.go as part of your solution.
```

I feel clarifying the `matrix.go` file should also be submitted is helpful.

**Review by andrerfcsantos — CHANGES_REQUESTED** [review]

**Review by andrerfcsantos — APPROVED** [review]
Thanks!
